<?xml version="1.0" encoding="utf-8"?><Database Name="HotelBooking" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Admins" Member="Admins">
    <Type Name="Admin">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="User_Admin" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DeletedAt" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Association Name="User_Admin" Member="Admin" ThisKey="Id" OtherKey="UserId" Type="Admin" Cardinality="One" />
      <Association Name="User_Booking" Member="Bookings" ThisKey="Id" OtherKey="UserId" Type="Booking" />
      <Association Name="User_Customer" Member="Customer" ThisKey="Id" OtherKey="UserId" Type="Customer" Cardinality="One" />
      <Association Name="User_Review" Member="Reviews" ThisKey="Id" OtherKey="UserId" Type="Review" />
    </Type>
  </Table>
  <Table Name="dbo.Bookings" Member="Bookings">
    <Type Name="Booking">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HotelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoomId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CheckInDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="CheckOutDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Guests" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PricePerNight" Type="System.Decimal" DbType="Decimal(12,2) NOT NULL" CanBeNull="false" />
      <Column Name="Nights" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubTotal" Type="System.Decimal" DbType="Decimal(14,2) NOT NULL" CanBeNull="false" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(14,2) NOT NULL" CanBeNull="false" />
      <Column Name="PromotionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FreeCancellationDeadline" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="PenaltyAmount" Type="System.Decimal" DbType="Decimal(14,2)" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedAt" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="CancelledAt" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="DeletedAt" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Booking_Payment" Member="Payments" ThisKey="Id" OtherKey="BookingId" Type="Payment" />
      <Association Name="Booking_Review" Member="Reviews" ThisKey="Id" OtherKey="BookingId" Type="Review" />
      <Association Name="User_Booking" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="Hotel_Booking" Member="Hotel" ThisKey="HotelId" OtherKey="Id" Type="Hotel" IsForeignKey="true" />
      <Association Name="Promotion_Booking" Member="Promotion" ThisKey="PromotionId" OtherKey="Id" Type="Promotion" IsForeignKey="true" />
      <Association Name="Room_Booking" Member="Room" ThisKey="RoomId" OtherKey="Id" Type="Room" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LoyaltyTierId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalPoints" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Customer" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="LoyaltyTier_Customer" Member="LoyaltyTier" ThisKey="LoyaltyTierId" OtherKey="Id" Type="LoyaltyTier" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HotelImages" Member="HotelImages">
    <Type Name="HotelImage">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HotelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="AltText" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Hotel_HotelImage" Member="Hotel" ThisKey="HotelId" OtherKey="Id" Type="Hotel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Hotels" Member="Hotels">
    <Type Name="Hotel">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="StarRating" Type="System.Decimal" DbType="Decimal(2,1)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeletedAt" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedAt" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Association Name="Hotel_Booking" Member="Bookings" ThisKey="Id" OtherKey="HotelId" Type="Booking" />
      <Association Name="Hotel_HotelImage" Member="HotelImages" ThisKey="Id" OtherKey="HotelId" Type="HotelImage" />
      <Association Name="Hotel_Room" Member="Rooms" ThisKey="Id" OtherKey="HotelId" Type="Room" />
    </Type>
  </Table>
  <Table Name="dbo.LoyaltyTiers" Member="LoyaltyTiers">
    <Type Name="LoyaltyTier">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DiscountPercent" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="Multiplier" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="MinPoints" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Association Name="LoyaltyTier_Customer" Member="Customers" ThisKey="Id" OtherKey="LoyaltyTierId" Type="Customer" />
    </Type>
  </Table>
  <Table Name="dbo.Payments" Member="Payments">
    <Type Name="Payment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BookingId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(14,2) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="PaidAt" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Association Name="Booking_Payment" Member="Booking" ThisKey="BookingId" OtherKey="Id" Type="Booking" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Promotions" Member="Promotions">
    <Type Name="Promotion">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Decimal" DbType="Decimal(12,2) NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DeletedAt" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedAt" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Association Name="Promotion_Booking" Member="Bookings" ThisKey="Id" OtherKey="PromotionId" Type="Booking" />
    </Type>
  </Table>
  <Table Name="dbo.Reviews" Member="Reviews">
    <Type Name="Review">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BookingId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Rating" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedAt" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="DeletedAt" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Association Name="Booking_Review" Member="Booking" ThisKey="BookingId" OtherKey="Id" Type="Booking" IsForeignKey="true" />
      <Association Name="User_Review" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RoomImages" Member="RoomImages">
    <Type Name="RoomImage">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoomId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="AltText" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Room_RoomImage" Member="Room" ThisKey="RoomId" OtherKey="Id" Type="Room" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rooms" Member="Rooms">
    <Type Name="Room">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HotelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RoomNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Capacity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PricePerNight" Type="System.Decimal" DbType="Decimal(12,2) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DeletedAt" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedAt" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Association Name="Room_Booking" Member="Bookings" ThisKey="Id" OtherKey="RoomId" Type="Booking" />
      <Association Name="Room_RoomImage" Member="RoomImages" ThisKey="Id" OtherKey="RoomId" Type="RoomImage" />
      <Association Name="Hotel_Room" Member="Hotel" ThisKey="HotelId" OtherKey="Id" Type="Hotel" IsForeignKey="true" />
    </Type>
  </Table>
</Database>